using UnityEngine;

namespace NavianChallenge.UI
{
    /// <summary>
    /// Creates the challenge HUD at Play start without needing anything baked into the
    /// scene file — the base .unity stays exactly as generated by ChallengeSceneBuilder.
    /// </summary>
    public static class ChallengeUIBootstrap
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void Init()
        {
            if (Object.FindAnyObjectByType<ChallengeHUD>() != null) return;
            var go = new GameObject("ChallengeUI");
            go.AddComponent<ChallengeHUD>();
        }
    }
}
